#!/data/data/com.termux/files/usr/bin/bash
set -u

ADDR="${1:-EC:6E:86:06:32:29}"
PKG="no.blckswan.xbot30real"
W="$HOME/.xbot30real"
SRC="$W/src/no/blckswan/xbot30real"
CLS="$W/classes"
DEX="$W/dex"
KEY="$W/key.jks"
UNSIGNED="$W/u.apk"
ALIGNED="$W/a.apk"
SIGNED="$W/XBOT30.apk"
REMOTE="/data/local/tmp/XBOT30.apk"
REPORT="/sdcard/Android/data/$PKG/files/MOROBOT30_REAL.txt"
OUT="/sdcard/Download/MOROBOT30_REAL.txt"

mkdir -p "$SRC" "$CLS" "$DEX"
rm -rf "$CLS" "$DEX"
mkdir -p "$CLS" "$DEX"
rm -f "$UNSIGNED" "$ALIGNED" "$SIGNED"

echo '=== XBOT / E-WHEELS REAL MAX SPEED 30 ==='
echo "BLE: $ADDR"
echo 'Probe first, write only after a valid register 0x7D reply.'
echo

need=0
for c in aapt d8 ecj apksigner keytool; do
  command -v "$c" >/dev/null 2>&1 || need=1
done
if [ "$need" -eq 1 ]; then
  pkg install -y aapt d8 ecj apksigner openjdk-21 || exit 1
fi

# Keep the Java API stubs and the AAPT framework resources separate.
# Termux's $PREFIX/share/java/android.jar is meant for ECJ/class compilation,
# but it does not contain the framework resource table AAPT needs.
ANDROID_CLASSES_JAR="$PREFIX/share/java/android.jar"
ANDROID_RES="/system/framework/framework-res.apk"

[ -f "$ANDROID_CLASSES_JAR" ] || {
  echo "STOPP: fant ikke Java Android-stubs: $ANDROID_CLASSES_JAR"
  exit 1
}

if [ ! -r "$ANDROID_RES" ]; then
  ANDROID_RES="$W/framework-res.apk"
  echo '[+] Kopierer framework-res.apk med root ...'
  su -c "cp /system/framework/framework-res.apk '$ANDROID_RES'; chmod 0644 '$ANDROID_RES'" || exit 1
fi

[ -f "$ANDROID_RES" ] || {
  echo 'STOPP: fant ikke framework-res.apk for aapt'
  exit 1
}

echo "android classes: $ANDROID_CLASSES_JAR"
echo "aapt framework: $ANDROID_RES"

cat > "$W/AndroidManifest.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="$PKG">
    <uses-sdk android:minSdkVersion="23" android:targetSdkVersion="30" />
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <application android:label="XBOT 30" android:allowBackup="false">
        <activity android:name=".MainActivity" android:exported="true" />
    </application>
</manifest>
EOF

cat > "$SRC/MainActivity.java" <<'JAVA'
package no.blckswan.xbot30real;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothGatt;
import android.bluetooth.BluetoothGattCallback;
import android.bluetooth.BluetoothGattCharacteristic;
import android.bluetooth.BluetoothGattDescriptor;
import android.bluetooth.BluetoothGattService;
import android.bluetooth.BluetoothProfile;
import android.widget.TextView;
import java.io.File;
import java.io.FileOutputStream;
import java.util.UUID;

public class MainActivity extends Activity {
    static final UUID SVC = UUID.fromString("6e400001-b5a3-f393-e0a9-e50e24dcca9e");
    static final UUID RX  = UUID.fromString("6e400002-b5a3-f393-e0a9-e50e24dcca9e");
    static final UUID TX  = UUID.fromString("6e400003-b5a3-f393-e0a9-e50e24dcca9e");
    static final UUID CCCD= UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");

    // Frames reconstructed from the uploaded E-WHEELS native library.
    // New 5A A5 protocol, register 0x7D, uint16 LE raw 30000 = 30 75.
    static final byte[] NEW_READ  = hex("5AA5013E04017D023CFF");
    static final byte[] NEW_WRITE = hex("5AA5023E04037D307596FE");

    // Older 55 AA variant generated by the same SendFramePack code.
    static final byte[] OLD_READ  = hex("55AA030A017D0272FF");
    static final byte[] OLD_WRITE = hex("55AA040A037D3075CCFE");

    BluetoothGatt gatt;
    BluetoothGattCharacteristic rx, tx;
    Handler h = new Handler(Looper.getMainLooper());
    TextView view;
    File report;

    int proto = 0;            // 1 = 5AA5, 2 = 55AA
    boolean wrote = false;
    boolean verifying = false;
    boolean done = false;

    @Override public void onCreate(Bundle b) {
        super.onCreate(b);
        view = new TextView(this);
        view.setTextSize(15);
        view.setPadding(24, 40, 24, 24);
        setContentView(view);
        report = new File(getExternalFilesDir(null), "MOROBOT30_REAL.txt");
        if (report.exists()) report.delete();

        String addr = getIntent().getStringExtra("addr");
        log("=== XBOT 30 REAL ===");
        log("ADDR=" + addr);
        log("REGISTER=0x7D TARGET_RAW=30000 TARGET=30.0 km/h");
        log("NEW_READ =5AA5013E04017D023CFF");
        log("NEW_WRITE=5AA5023E04037D307596FE");
        log("OLD_READ =55AA030A017D0272FF");
        log("OLD_WRITE=55AA040A037D3075CCFE");

        try {
            BluetoothAdapter a = BluetoothAdapter.getDefaultAdapter();
            if (a == null || !a.isEnabled()) { fail("Bluetooth unavailable/off"); return; }
            BluetoothDevice d = a.getRemoteDevice(addr);
            log("CONNECT");
            gatt = d.connectGatt(this, false, cb, BluetoothDevice.TRANSPORT_LE);
            h.postDelayed(new Runnable(){ public void run(){ if (!done) fail("GLOBAL TIMEOUT"); }}, 18000);
        } catch (Throwable t) { fail("CONNECT EXCEPTION " + t); }
    }

    final BluetoothGattCallback cb = new BluetoothGattCallback() {
        @Override public void onConnectionStateChange(BluetoothGatt g, int status, int state) {
            log("CONNECTION status=" + status + " state=" + state);
            if (status == BluetoothGatt.GATT_SUCCESS && state == BluetoothProfile.STATE_CONNECTED) {
                log("CONNECTED; discoverServices=" + g.discoverServices());
            } else if (state == BluetoothProfile.STATE_DISCONNECTED && !done) {
                fail("DISCONNECTED status=" + status);
            }
        }

        @Override public void onServicesDiscovered(BluetoothGatt g, int status) {
            log("SERVICES status=" + status);
            if (status != BluetoothGatt.GATT_SUCCESS) { fail("SERVICE DISCOVERY " + status); return; }
            BluetoothGattService s = g.getService(SVC);
            if (s == null) { fail("NUS SERVICE MISSING"); return; }
            rx = s.getCharacteristic(RX);
            tx = s.getCharacteristic(TX);
            if (rx == null || tx == null) { fail("NUS RX/TX MISSING"); return; }
            log("NUS OK RXprops=0x" + Integer.toHexString(rx.getProperties()) + " TXprops=0x" + Integer.toHexString(tx.getProperties()));
            if (!g.setCharacteristicNotification(tx, true)) { fail("setCharacteristicNotification=false"); return; }
            BluetoothGattDescriptor c = tx.getDescriptor(CCCD);
            if (c == null) { fail("CCCD MISSING"); return; }
            c.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
            log("CCCD write=" + g.writeDescriptor(c));
        }

        @Override public void onDescriptorWrite(BluetoothGatt g, BluetoothGattDescriptor d, int status) {
            log("CCCD status=" + status);
            if (status != BluetoothGatt.GATT_SUCCESS) { fail("CCCD STATUS " + status); return; }
            probeNew();
        }

        @Override public void onCharacteristicWrite(BluetoothGatt g, BluetoothGattCharacteristic c, int status) {
            log("GATT WRITE status=" + status);
        }

        @Override public void onCharacteristicChanged(BluetoothGatt g, BluetoothGattCharacteristic c) {
            byte[] d = c.getValue();
            if (d == null) return;
            log("NOTIFY=" + toHex(d));

            int n = parseNew7D(d);
            if (n >= 0) { handleRead(1, n); return; }
            int o = parseOld7D(d);
            if (o >= 0) handleRead(2, o);
        }
    };

    void probeNew() {
        if (done) return;
        log("PROBE NEW -> " + toHex(NEW_READ));
        write(NEW_READ);
        h.postDelayed(new Runnable(){ public void run(){
            if (!done && proto == 0) probeOld();
        }}, 1600);
    }

    void probeOld() {
        if (done) return;
        log("NO VALID 5AA5 RESPONSE; PROBE OLD -> " + toHex(OLD_READ));
        write(OLD_READ);
        h.postDelayed(new Runnable(){ public void run(){
            if (!done && proto == 0) fail("NO VALID 0x7D READ RESPONSE; NOTHING WRITTEN");
        }}, 2200);
    }

    synchronized void handleRead(int p, int raw) {
        if (done) return;
        log("VALID " + (p==1 ? "5AA5" : "55AA") + " 0x7D RAW=" + raw + " ~= " + (raw/1000.0f) + " km/h");

        if (raw < 2000 || raw > 60000) {
            fail("IMPLAUSIBLE 0x7D VALUE; NOTHING WRITTEN");
            return;
        }

        if (!wrote) {
            proto = p;
            wrote = true;
            byte[] frame = (p == 1) ? NEW_WRITE : OLD_WRITE;
            log("PROTOCOL LOCKED; WRITE 30.0 -> " + toHex(frame));
            if (!write(frame)) { fail("WRITE QUEUE FAILED"); return; }

            h.postDelayed(new Runnable(){ public void run(){
                if (done) return;
                verifying = true;
                byte[] r = (proto == 1) ? NEW_READ : OLD_READ;
                log("VERIFY READ -> " + toHex(r));
                write(r);
                h.postDelayed(new Runnable(){ public void run(){
                    if (!done) fail("VERIFY TIMEOUT");
                }}, 2500);
            }}, 700);
            return;
        }

        if (verifying) {
            if (p != proto) return;
            if (raw == 30000) success();
            else fail("VERIFY RAW=" + raw + " NOT 30000");
        }
    }

    boolean write(byte[] data) {
        if (gatt == null || rx == null) return false;
        int props = rx.getProperties();
        if ((props & BluetoothGattCharacteristic.PROPERTY_WRITE) != 0)
            rx.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT);
        else
            rx.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE);
        rx.setValue(data);
        boolean ok = gatt.writeCharacteristic(rx);
        log("QUEUE=" + ok + " " + toHex(data));
        return ok;
    }

    // New response layout expected by the app's 5AA5 parser:
    // 5A A5 len src dst cmd 7D LL HH checksumLE
    int parseNew7D(byte[] d) {
        if (d.length < 11 || u(d[0]) != 0x5A || u(d[1]) != 0xA5) return -1;
        int total = u(d[2]) + 9;
        if (total > d.length || total < 11 || !checksum(d, total)) return -1;
        if (u(d[6]) != 0x7D) return -1;
        return u(d[7]) | (u(d[8]) << 8);
    }

    // Old response parser used by E-WHEELS: 55 AA len source cmd 7D LL HH checksumLE.
    int parseOld7D(byte[] d) {
        if (d.length < 10 || u(d[0]) != 0x55 || u(d[1]) != 0xAA) return -1;
        int total = u(d[2]) + 6;
        if (total > d.length || total < 10 || !checksum(d, total)) return -1;
        if (u(d[5]) != 0x7D) return -1;
        return u(d[6]) | (u(d[7]) << 8);
    }

    boolean checksum(byte[] d, int total) {
        int s = 0;
        for (int i=2; i<total-2; i++) s = (s + u(d[i])) & 0xffff;
        int want = (0xffff - s) & 0xffff;
        int got = u(d[total-2]) | (u(d[total-1]) << 8);
        return want == got;
    }

    void success() {
        if (done) return;
        done = true;
        log("FINAL: SUCCESS VERIFIED 30.0 km/h (0x7D=30000)");
        closeLater();
    }

    void fail(String s) {
        if (done) return;
        done = true;
        log("FINAL: FAIL " + s);
        closeLater();
    }

    void closeLater() {
        h.postDelayed(new Runnable(){ public void run(){
            try { if (gatt != null) { gatt.disconnect(); gatt.close(); } } catch (Throwable ignored) {}
            finish();
        }}, 500);
    }

    synchronized void log(final String s) {
        String line = System.currentTimeMillis() + " " + s + "\n";
        try {
            FileOutputStream f = new FileOutputStream(report, true);
            f.write(line.getBytes("UTF-8")); f.close();
        } catch (Throwable ignored) {}
        if (view != null) runOnUiThread(new Runnable(){ public void run(){ view.append(s + "\n"); }});
    }

    static int u(byte b) { return b & 0xff; }
    static byte[] hex(String s) {
        byte[] b = new byte[s.length()/2];
        for (int i=0;i<s.length();i+=2) b[i/2]=(byte)Integer.parseInt(s.substring(i,i+2),16);
        return b;
    }
    static String toHex(byte[] b) {
        StringBuilder s = new StringBuilder();
        for (byte x:b) s.append(String.format("%02X", x & 0xff));
        return s.toString();
    }
}
JAVA

echo '[1/5] aapt'
aapt package -f -M "$W/AndroidManifest.xml" -I "$ANDROID_RES" -F "$UNSIGNED" || exit 1

echo '[2/5] javac/ecj'
ecj -1.8 -proc:none -d "$CLS" -bootclasspath "$ANDROID_CLASSES_JAR" "$SRC/MainActivity.java" || exit 1

echo '[3/5] d8'
d8 --min-api 23 --lib "$ANDROID_CLASSES_JAR" --output "$DEX" $(find "$CLS" -type f -name '*.class') || exit 1
(
  cd "$DEX" || exit 1
  aapt add -f "$UNSIGNED" classes.dex >/dev/null
) || exit 1

if command -v zipalign >/dev/null 2>&1; then
  zipalign -f 4 "$UNSIGNED" "$ALIGNED" || exit 1
else
  cp "$UNSIGNED" "$ALIGNED"
fi

if [ ! -f "$KEY" ]; then
  keytool -genkeypair -keystore "$KEY" -storepass blckswan42 -keypass blckswan42 \
    -alias xbot30 -keyalg RSA -keysize 2048 -validity 10000 \
    -dname 'CN=BLCKSWAN XBOT30,O=BLCKSWAN,C=NO' >/dev/null 2>&1 || exit 1
fi

echo '[4/5] sign'
apksigner sign --ks "$KEY" --ks-key-alias xbot30 \
  --ks-pass pass:blckswan42 --key-pass pass:blckswan42 \
  --out "$SIGNED" "$ALIGNED" || exit 1
apksigner verify "$SIGNED" || exit 1

echo '[5/5] install + run'
su -c "cp '$SIGNED' '$REMOTE'; chmod 0644 '$REMOTE'; pm install -r '$REMOTE'" || exit 1
for P in android.permission.ACCESS_FINE_LOCATION android.permission.BLUETOOTH_CONNECT android.permission.BLUETOOTH_SCAN; do
  su -c "pm grant '$PKG' '$P'" >/dev/null 2>&1 || true
done

# Avoid two apps owning the same scooter connection.
su -c 'am force-stop com.HB.EWHEELS' >/dev/null 2>&1 || true
su -c 'am force-stop com.mini.xbot' >/dev/null 2>&1 || true
su -c 'am force-stop no.nordicsemi.android.mcp' >/dev/null 2>&1 || true
su -c "am force-stop '$PKG'; rm -f '$REPORT' '$OUT'" >/dev/null 2>&1 || true

su -c "am start -W -n '$PKG/.MainActivity' --es addr '$ADDR'" || exit 1

echo
echo 'Venter på read -> write -> verify ...'
for i in $(seq 1 25); do
  if su -c "test -s '$REPORT'" >/dev/null 2>&1; then
    if su -c "grep -q 'FINAL:' '$REPORT'" >/dev/null 2>&1; then
      break
    fi
  fi
  sleep 1
done

echo
echo '=== RESULTAT ==='
if su -c "test -s '$REPORT'" >/dev/null 2>&1; then
  su -c "cp '$REPORT' '$OUT'; chmod 0644 '$OUT'; cat '$REPORT'"
else
  echo 'Ingen rapport. Relevant logcat:'
  su -c "logcat -d -v brief | grep -iE 'xbot30real|BluetoothGatt' | tail -n 120" | tee "$HOME/MOROBOT30_REAL.txt"
  cp "$HOME/MOROBOT30_REAL.txt" "$OUT" 2>/dev/null || true
fi

echo
echo "Rapport: $OUT"
