#!/usr/bin/env node
import {readdir,readFile,stat} from 'node:fs/promises';import {createHash} from 'node:crypto';import {join,basename} from 'node:path';
const KNOWN={pro:{sha:'856c19b176f9e8d1f73f627e731e4a991282c9fba2a136b14651831b981bff62',size:28444,profile:'v2-pro-lr'}};
const pats=[['NUS service',/6e400001[-:]?b5a3/i,25],['NUS RX',/6e400002[-:]?b5a3/i,10],['NUS TX',/6e400003[-:]?b5a3/i,10],['MORO42001',/MORO42001/i,15],['MOROBOT identity',/M0?ROBOT|MOROBOT/i,10],['HB F3 register',/(^|\W)F3(\W|$)/i,5],['DK ID 061007f9',/061007f9/i,25]];
async function files(p,out=[]){try{let s=await stat(p);if(s.isFile()){out.push(p);return out}for(let n of await readdir(p))await files(join(p,n),out)}catch{}return out}
async function hash(p){let b=await readFile(p);return {sha:createHash('sha256').update(b).digest('hex'),size:b.length}}
async function scan(root){let fs=await files(root),hits=[],score=0,known=[];for(let f of fs){let name=basename(f);if(/\.bin$/i.test(f)){try{let h=await hash(f);if(h.sha===KNOWN.pro.sha&&h.size===KNOWN.pro.size)known.push({file:f,...h,profile:KNOWN.pro.profile})}catch{}}if(!/\.(txt|log|json|xml|md|conf|ini|sh)$/i.test(f)&&!/^DK.*\.bin$/i.test(name))continue;try{let b=await readFile(f);let t=b.toString('utf8');for(let [label,re,w] of pats)if(re.test(t)||re.test(name)){hits.push({label,file:f});score+=w}}catch{}}
score=Math.min(score+(known.length?60:0),100);let profile=known.length?'v2-pro-lr':'unknown';console.log(JSON.stringify({root,files_scanned:fs.length,profile,confidence:score,verified_firmware:known,hits:[...new Map(hits.map(x=>[x.label+'|'+x.file,x])).values()],next:known.length?'Verified current DK found. Use MOROSAMT run; keep manual flash confirmation.':score>=30?'Run probe/capture and collect controller-side evidence.':'Collect BLE/GATT fingerprint first; do not choose firmware.'},null,2))}
async function inspect(p){let h=await hash(p);let match=Object.values(KNOWN).find(x=>x.sha===h.sha&&x.size===h.size);console.log(JSON.stringify({file:p,...h,match:match?.profile||null},null,2))}
let [cmd='scan',arg='/sdcard/Download']=process.argv.slice(2);if(cmd==='scan')await scan(arg);else if(cmd==='inspect')await inspect(arg);else{console.error('Usage: node morosamt-find.mjs scan [PATH] | inspect FILE');process.exit(2)}